### ISSUE TITLE
Issue while using it java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by vishalx4** [Aghajari/LazySwipeCards#2]
# Error
java.lang.IncompatibleClassChangeError: Class com.aghajari.compose.lazyswipecards.LazySwipeCardsIntervalContent implements non-interface class androidx.compose.foundation.lazy.layout.LazyLayoutIntervalContent (declaration of 'com.aghajari.compose.lazyswipecards.LazySwipeCardsIntervalContent' appears in /data/app/~~Jgg1c_9-vvkA-lA6zklSwA==/com.styledotme.radbeauty-DnESJ_oht3gxfqrlsXHFFQ==/base.apk!classes9.dex)
                                                                                                    	at com.aghajari.compose.lazyswipecards.LazySwipeCardsItemProviderKt.rememberLazySwipeCardsItemProvider

**Comment by EgorBron** [comment]
Got the same issue while using Compose 1.6.1 (Compose BOM 2024.02.00).
As I see, the problem occurs at `LazySwipeCardsIntervalContent`: in Compose 1.5.0 the `LazyLayoutIntervalContent` now has a generic parameter [`Interval`](https://developer.android.com/reference/kotlin/androidx/compose/foundation/lazy/layout/LazyLayoutIntervalContent.Interval).
https://github.com/Aghajari/LazySwipeCards/blob/ea3016930e7ec2ffbb5269ee00883b2dae7e4489/LazySwipeCards/src/main/java/com/aghajari/compose/lazyswipecards/LazySwipeCardsScope.kt#L72-L75

I also noticed that compiler complains about `DefaultLazyLayoutItemsProvider.Item(Int)` (missing `key` parameter) and the class definition (`getKey` not implemented). LazyLayoutItemProvider got updated in Compose 1.5.0 (see [LazyLayoutItemProvider](https://developer.android.com/reference/kotlin/androidx/compose/foundation/lazy/layout/LazyLayoutItemProvider))
https://github.com/Aghajari/LazySwipeCards/blob/ea3016930e7ec2ffbb5269ee00883b2dae7e4489/LazySwipeCards/src/main/java/com/aghajari/compose/lazyswipecards/LazySwipeCardsItemProvider.kt#L123

Downgrading to Compose BOM 2023.06.01 in the project dependences resolved both of issues for me, but I can't use such an old version of Compose.

**Comment by Aghajari** [comment]
Hello @vishalx4 and @EgorBron ,

The library has been updated to version 1.0.1. This update includes compatibility with the latest version of Compose-BOM (2024.02.01). Cheers!

**Comment by EgorBron** [comment]
> The library has been updated to version 1.0.1. This update includes compatibility with the latest version of Compose-BOM (2024.02.01). Cheers!

Hello @Aghajari!
The library works perfectly now. Thank you very much!
